# Schema for the configuration files of the nopremium module.
nopremium.settings:
  type: config_object
  label: 'Node option premium settings'
  mapping:
    default_message:
      type: string
      label: 'Premium message'
    messages:
      type: sequence
      label: 'Message per content type'
      sequence:
        type: string
    view_modes:
      type: sequence
      label: 'Premium view modes'
      sequence:
        type: string
    teaser_view_mode:
      type: string
      label: 'Teaser view mode'
